In [1]:
pip install numpy



[notice] A new release of pip is available: 23.3 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
arr = np.array(42)  # 0 demension arry
print(arr)
print(arr.ndim)


42
0


In [6]:
 # 1 demension arry
arr = np.array([1,2,3,4,5,6,7,8,9,0]) 
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7 8 9 0]
1


In [7]:
 # 2 demension arry
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]]) 
print(arr)
print(arr.ndim)

[[1 2 3 4 5]
 [6 7 8 9 0]]
2


In [9]:
 # 3 demension arry
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]]) 
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
3


In [11]:
 # 3 demension arry
arr = np.array([[[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]],[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]]]) 
print(arr)
print(arr.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]]]
4
